name:                vinyltest
version:             0.1.0.0
synopsis:            Simple project template from stack
description:         Please see README.md
homepage:            https://github.com/githubuser/vinyltest#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2017 Author name here
category:            Web

dependencies:
  - base >= 4.7 && < 5
  - vinyl
  - Frames
  - aeson
  - aeson-better-errors
  - classy-prelude
  - lens

default-extensions:
  - DataKinds
  - FlexibleInstances
  - NoImplicitPrelude
  - OverloadedStrings
  - PolyKinds
  - ScopedTypeVariables
  - StrictData
  - TypeFamilies
  - TypeOperators

ghc-options: -Wall -Werror -O2

executables:
  vinyltest:
    source-dirs:      src
    main:             Main.hs
